name: Build RevoMC

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install customtkinter certifi pyinstaller

      - name: Build exe
        run: |
          pyinstaller revomc.spec --distpath builds/

      - name: Zip the exe
        run: |
          Compress-Archive -Path builds/RevoMC.exe -DestinationPath RevoMC-windows.zip

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: RevoMC-windows.zip
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_RELEASE_TOKEN }}

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install customtkinter certifi pyinstaller

      - name: Build app
        run: |
          pyinstaller revomc.spec --distpath builds/

      - name: Zip the app
        run: |
          cd builds
          zip -r ../RevoMC-macos.zip RevoMC.app

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: RevoMC-macos.zip
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_RELEASE_TOKEN }}

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-tk

      - name: Install dependencies
        run: |
          pip install customtkinter certifi pyinstaller

      - name: Build app
        run: |
          pyinstaller revomc.spec --distpath builds/

      - name: Zip the app
        run: |
          cd builds
          zip -r ../RevoMC-linux.zip RevoMC/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: RevoMC-linux.zip
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_RELEASE_TOKEN }}